### ISSUE TITLE
convert-units 3.0.0-beta.6 import

### ISSUE THREAD

**Issue by md-es** [crotwell/seisplotjs#39]
seisplotjs 3.1.3 works fine with convert-units 3.0.0-beta.5. As package.json has dependency
    "convert-units": "^3.0.0-beta.5",
it picked up next beta that causes the export error.

✘ [ERROR] No matching export in "node_modules/convert-units/lib/esm/index.js" for import "allMeasures"

    node_modules/seisplotjs/dist/index.esm.js:25481:32:
      25481 │ import configureMeasurements, { allMeasures } from "convert-units";
            ╵                                 ~~~~~~~~~~~

2:51:24 PM [vite] error while updating dependencies:
Error: Build failed with 1 error:
node_modules/seisplotjs/dist/index.esm.js:25481:32: ERROR: No matching export in "node_modules/convert-units/lib/esm/index.js" for import "allMeasures"

I would lock it to a specific version or update how the import is happening. With update there are not guaranties that it won't happen again.

**Comment by crotwell** [comment]
updated code to workwith convert-units 3.0.0 beta6, in ver 3.1.4
